/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AdminMMRRecalculateMMRRequest {
    fromMatchId?: number;
}

/**
 * 
 */
export class AdminMMRApi extends runtime.BaseAPI {

    /**
     */
    async adminMMRRecalculateMMRRaw(requestParameters: AdminMMRRecalculateMMRRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['fromMatchId'] != null) {
            queryParameters['fromMatchId'] = requestParameters['fromMatchId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/admin/mmr/recalculate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminMMRRecalculateMMR(requestParameters: AdminMMRRecalculateMMRRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminMMRRecalculateMMRRaw(requestParameters, initOverrides);
    }

}
