/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MatchDetailsV2,
  UpdateMatchRequest,
} from '../models/index';
import {
    MatchDetailsV2FromJSON,
    MatchDetailsV2ToJSON,
    UpdateMatchRequestFromJSON,
    UpdateMatchRequestToJSON,
} from '../models/index';

export interface AdminMatchDeleteMatchRequest {
    matchId: number;
}

export interface AdminMatchUpdateMatchRequest {
    matchId: number;
    updateMatchRequest?: UpdateMatchRequest;
}

/**
 * 
 */
export class AdminMatchApi extends runtime.BaseAPI {

    /**
     */
    async adminMatchDeleteMatchRaw(requestParameters: AdminMatchDeleteMatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['matchId'] == null) {
            throw new runtime.RequiredError(
                'matchId',
                'Required parameter "matchId" was null or undefined when calling adminMatchDeleteMatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/admin/matches/{matchId}`.replace(`{${"matchId"}}`, encodeURIComponent(String(requestParameters['matchId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminMatchDeleteMatch(requestParameters: AdminMatchDeleteMatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminMatchDeleteMatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async adminMatchUpdateMatchRaw(requestParameters: AdminMatchUpdateMatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchDetailsV2>> {
        if (requestParameters['matchId'] == null) {
            throw new runtime.RequiredError(
                'matchId',
                'Required parameter "matchId" was null or undefined when calling adminMatchUpdateMatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/admin/matches/{matchId}`.replace(`{${"matchId"}}`, encodeURIComponent(String(requestParameters['matchId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMatchRequestToJSON(requestParameters['updateMatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchDetailsV2FromJSON(jsonValue));
    }

    /**
     */
    async adminMatchUpdateMatch(requestParameters: AdminMatchUpdateMatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchDetailsV2> {
        const response = await this.adminMatchUpdateMatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
