/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MatchFlagDetails,
  UpdateMatchFlagRequest,
} from '../models/index';
import {
    MatchFlagDetailsFromJSON,
    MatchFlagDetailsToJSON,
    UpdateMatchFlagRequestFromJSON,
    UpdateMatchFlagRequestToJSON,
} from '../models/index';

export interface AdminMatchFlagsUpdateFlagRequest {
    id: number;
    updateMatchFlagRequest?: UpdateMatchFlagRequest;
}

/**
 * 
 */
export class AdminMatchFlagsApi extends runtime.BaseAPI {

    /**
     */
    async adminMatchFlagsGetPendingFlagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MatchFlagDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/admin/match-flags`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MatchFlagDetailsFromJSON));
    }

    /**
     */
    async adminMatchFlagsGetPendingFlags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MatchFlagDetails>> {
        const response = await this.adminMatchFlagsGetPendingFlagsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async adminMatchFlagsUpdateFlagRaw(requestParameters: AdminMatchFlagsUpdateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminMatchFlagsUpdateFlag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/admin/match-flags/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMatchFlagRequestToJSON(requestParameters['updateMatchFlagRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminMatchFlagsUpdateFlag(requestParameters: AdminMatchFlagsUpdateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminMatchFlagsUpdateFlagRaw(requestParameters, initOverrides);
    }

}
