/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChipRegistrationRequest,
} from '../models/index';
import {
    ChipRegistrationRequestFromJSON,
    ChipRegistrationRequestToJSON,
} from '../models/index';

export interface ChipPostRequest {
    chipRegistrationRequest?: ChipRegistrationRequest;
}

/**
 * 
 */
export class ChipApi extends runtime.BaseAPI {

    /**
     */
    async chipPostRaw(requestParameters: ChipPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chip-registration`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChipRegistrationRequestToJSON(requestParameters['chipRegistrationRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async chipPost(requestParameters: ChipPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.chipPostRaw(requestParameters, initOverrides);
    }

}
