/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMatchFlagRequest,
  UpdateMatchFlagReasonRequest,
  UserMatchFlag,
} from '../models/index';
import {
    CreateMatchFlagRequestFromJSON,
    CreateMatchFlagRequestToJSON,
    UpdateMatchFlagReasonRequestFromJSON,
    UpdateMatchFlagReasonRequestToJSON,
    UserMatchFlagFromJSON,
    UserMatchFlagToJSON,
} from '../models/index';

export interface MatchFlagsCreateFlagRequest {
    createMatchFlagRequest?: CreateMatchFlagRequest;
}

export interface MatchFlagsDeleteFlagRequest {
    id: number;
}

export interface MatchFlagsUpdateFlagRequest {
    id: number;
    updateMatchFlagReasonRequest?: UpdateMatchFlagReasonRequest;
}

/**
 * 
 */
export class MatchFlagsApi extends runtime.BaseAPI {

    /**
     */
    async matchFlagsCreateFlagRaw(requestParameters: MatchFlagsCreateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMatchFlag>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/match-flags`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMatchFlagRequestToJSON(requestParameters['createMatchFlagRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMatchFlagFromJSON(jsonValue));
    }

    /**
     */
    async matchFlagsCreateFlag(requestParameters: MatchFlagsCreateFlagRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMatchFlag> {
        const response = await this.matchFlagsCreateFlagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async matchFlagsDeleteFlagRaw(requestParameters: MatchFlagsDeleteFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling matchFlagsDeleteFlag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/match-flags/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async matchFlagsDeleteFlag(requestParameters: MatchFlagsDeleteFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.matchFlagsDeleteFlagRaw(requestParameters, initOverrides);
    }

    /**
     */
    async matchFlagsGetMyPendingFlagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserMatchFlag>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/match-flags/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserMatchFlagFromJSON));
    }

    /**
     */
    async matchFlagsGetMyPendingFlags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserMatchFlag>> {
        const response = await this.matchFlagsGetMyPendingFlagsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async matchFlagsUpdateFlagRaw(requestParameters: MatchFlagsUpdateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMatchFlag>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling matchFlagsUpdateFlag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/match-flags/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMatchFlagReasonRequestToJSON(requestParameters['updateMatchFlagReasonRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMatchFlagFromJSON(jsonValue));
    }

    /**
     */
    async matchFlagsUpdateFlag(requestParameters: MatchFlagsUpdateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMatchFlag> {
        const response = await this.matchFlagsUpdateFlagRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
