/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMatchFlagRequest,
} from '../models/index';
import {
    CreateMatchFlagRequestFromJSON,
    CreateMatchFlagRequestToJSON,
} from '../models/index';

export interface MatchesCreateFlagRequest {
    matchId: number;
    createMatchFlagRequest?: CreateMatchFlagRequest;
}

/**
 * 
 */
export class MatchesApi extends runtime.BaseAPI {

    /**
     */
    async matchesCreateFlagRaw(requestParameters: MatchesCreateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['matchId'] == null) {
            throw new runtime.RequiredError(
                'matchId',
                'Required parameter "matchId" was null or undefined when calling matchesCreateFlag().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/matches/{matchId}/flags`.replace(`{${"matchId"}}`, encodeURIComponent(String(requestParameters['matchId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMatchFlagRequestToJSON(requestParameters['createMatchFlagRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async matchesCreateFlag(requestParameters: MatchesCreateFlagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.matchesCreateFlagRaw(requestParameters, initOverrides);
    }

}
