/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PlayerRoleResponse,
} from '../models/index';
import {
    PlayerRoleResponseFromJSON,
    PlayerRoleResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class RolesApi extends runtime.BaseAPI {

    /**
     */
    async rolesGetMyRoleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayerRoleResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/roles/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayerRoleResponseFromJSON(jsonValue));
    }

    /**
     */
    async rolesGetMyRole(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayerRoleResponse> {
        const response = await this.rolesGetMyRoleRaw(initOverrides);
        return await response.value();
    }

}
