/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SeasonDto,
} from '../models/index';
import {
    SeasonDtoFromJSON,
    SeasonDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class SeasonsApi extends runtime.BaseAPI {

    /**
     */
    async seasonsGetSeasonsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SeasonDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/seasons`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SeasonDtoFromJSON));
    }

    /**
     */
    async seasonsGetSeasons(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SeasonDto>> {
        const response = await this.seasonsGetSeasonsRaw(initOverrides);
        return await response.value();
    }

}
