version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/mmr-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/api"
    schedule:
      interval: "weekly"
