version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/mmr-api"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
