FROM node:lts-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx svelte-kit sync && npx vite optimize
EXPOSE 5173
CMD ["sh", "-c", "npx svelte-kit sync && npx vite optimize && npm run dev -- --host 0.0.0.0"]
