/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveMatchSubmitRequest
 */
export interface ActiveMatchSubmitRequest {
    /**
     * 
     * @type {number}
     * @memberof ActiveMatchSubmitRequest
     */
    team1Score: number;
    /**
     * 
     * @type {number}
     * @memberof ActiveMatchSubmitRequest
     */
    team2Score: number;
}

/**
 * Check if a given object implements the ActiveMatchSubmitRequest interface.
 */
export function instanceOfActiveMatchSubmitRequest(value: object): boolean {
    if (!('team1Score' in value)) return false;
    if (!('team2Score' in value)) return false;
    return true;
}

export function ActiveMatchSubmitRequestFromJSON(json: any): ActiveMatchSubmitRequest {
    return ActiveMatchSubmitRequestFromJSONTyped(json, false);
}

export function ActiveMatchSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveMatchSubmitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'team1Score': json['team1Score'],
        'team2Score': json['team2Score'],
    };
}

export function ActiveMatchSubmitRequestToJSON(value?: ActiveMatchSubmitRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1Score': value['team1Score'],
        'team2Score': value['team2Score'],
    };
}

