/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveMatchTeamDto
 */
export interface ActiveMatchTeamDto {
    /**
     * 
     * @type {Array<number>}
     * @memberof ActiveMatchTeamDto
     */
    playerIds: Array<number>;
}

/**
 * Check if a given object implements the ActiveMatchTeamDto interface.
 */
export function instanceOfActiveMatchTeamDto(value: object): boolean {
    if (!('playerIds' in value)) return false;
    return true;
}

export function ActiveMatchTeamDtoFromJSON(json: any): ActiveMatchTeamDto {
    return ActiveMatchTeamDtoFromJSONTyped(json, false);
}

export function ActiveMatchTeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveMatchTeamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playerIds': json['playerIds'],
    };
}

export function ActiveMatchTeamDtoToJSON(value?: ActiveMatchTeamDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'playerIds': value['playerIds'],
    };
}

