/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerRole } from './PlayerRole';
import {
    PlayerRoleFromJSON,
    PlayerRoleFromJSONTyped,
    PlayerRoleToJSON,
} from './PlayerRole';

/**
 * 
 * @export
 * @interface AdminUserDetailsResponse
 */
export interface AdminUserDetailsResponse {
    /**
     * 
     * @type {number}
     * @memberof AdminUserDetailsResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailsResponse
     */
    identityUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailsResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailsResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDetailsResponse
     */
    displayName?: string;
    /**
     * 
     * @type {number}
     * @memberof AdminUserDetailsResponse
     */
    mmr?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminUserDetailsResponse
     */
    sigma?: number;
    /**
     * 
     * @type {PlayerRole}
     * @memberof AdminUserDetailsResponse
     */
    role?: PlayerRole;
    /**
     * 
     * @type {number}
     * @memberof AdminUserDetailsResponse
     */
    roleAssignedById?: number;
    /**
     * 
     * @type {Date}
     * @memberof AdminUserDetailsResponse
     */
    roleAssignedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminUserDetailsResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminUserDetailsResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AdminUserDetailsResponse
     */
    deletedAt?: Date;
}

/**
 * Check if a given object implements the AdminUserDetailsResponse interface.
 */
export function instanceOfAdminUserDetailsResponse(value: object): boolean {
    return true;
}

export function AdminUserDetailsResponseFromJSON(json: any): AdminUserDetailsResponse {
    return AdminUserDetailsResponseFromJSONTyped(json, false);
}

export function AdminUserDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'identityUserId': json['identityUserId'] == null ? undefined : json['identityUserId'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'mmr': json['mmr'] == null ? undefined : json['mmr'],
        'sigma': json['sigma'] == null ? undefined : json['sigma'],
        'role': json['role'] == null ? undefined : PlayerRoleFromJSON(json['role']),
        'roleAssignedById': json['roleAssignedById'] == null ? undefined : json['roleAssignedById'],
        'roleAssignedAt': json['roleAssignedAt'] == null ? undefined : (new Date(json['roleAssignedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
    };
}

export function AdminUserDetailsResponseToJSON(value?: AdminUserDetailsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'identityUserId': value['identityUserId'],
        'email': value['email'],
        'name': value['name'],
        'displayName': value['displayName'],
        'mmr': value['mmr'],
        'sigma': value['sigma'],
        'role': PlayerRoleToJSON(value['role']),
        'roleAssignedById': value['roleAssignedById'],
        'roleAssignedAt': value['roleAssignedAt'] == null ? undefined : ((value['roleAssignedAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
    };
}

