/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerRole } from './PlayerRole';
import {
    PlayerRoleFromJSON,
    PlayerRoleFromJSONTyped,
    PlayerRoleToJSON,
} from './PlayerRole';

/**
 * 
 * @export
 * @interface AssignRoleRequest
 */
export interface AssignRoleRequest {
    /**
     * 
     * @type {number}
     * @memberof AssignRoleRequest
     */
    playerId?: number;
    /**
     * 
     * @type {PlayerRole}
     * @memberof AssignRoleRequest
     */
    role?: PlayerRole;
}

/**
 * Check if a given object implements the AssignRoleRequest interface.
 */
export function instanceOfAssignRoleRequest(value: object): boolean {
    return true;
}

export function AssignRoleRequestFromJSON(json: any): AssignRoleRequest {
    return AssignRoleRequestFromJSONTyped(json, false);
}

export function AssignRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'playerId': json['playerId'] == null ? undefined : json['playerId'],
        'role': json['role'] == null ? undefined : PlayerRoleFromJSON(json['role']),
    };
}

export function AssignRoleRequestToJSON(value?: AssignRoleRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'playerId': value['playerId'],
        'role': PlayerRoleToJSON(value['role']),
    };
}

