/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChipRegistrationRequest
 */
export interface ChipRegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof ChipRegistrationRequest
     */
    chipId?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ChipRegistrationRequest
     */
    colorCode?: Array<number>;
}

/**
 * Check if a given object implements the ChipRegistrationRequest interface.
 */
export function instanceOfChipRegistrationRequest(value: object): boolean {
    return true;
}

export function ChipRegistrationRequestFromJSON(json: any): ChipRegistrationRequest {
    return ChipRegistrationRequestFromJSONTyped(json, false);
}

export function ChipRegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChipRegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chipId': json['chipId'] == null ? undefined : json['chipId'],
        'colorCode': json['colorCode'] == null ? undefined : json['colorCode'],
    };
}

export function ChipRegistrationRequestToJSON(value?: ChipRegistrationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chipId': value['chipId'],
        'colorCode': value['colorCode'],
    };
}

