/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimProfileRequest
 */
export interface ClaimProfileRequest {
    /**
     * 
     * @type {number}
     * @memberof ClaimProfileRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the ClaimProfileRequest interface.
 */
export function instanceOfClaimProfileRequest(value: object): boolean {
    if (!('userId' in value)) return false;
    return true;
}

export function ClaimProfileRequestFromJSON(json: any): ClaimProfileRequest {
    return ClaimProfileRequestFromJSONTyped(json, false);
}

export function ClaimProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function ClaimProfileRequestToJSON(value?: ClaimProfileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

