/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePersonalAccessTokenResponse
 */
export interface CreatePersonalAccessTokenResponse {
    /**
     * 
     * @type {number}
     * @memberof CreatePersonalAccessTokenResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalAccessTokenResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalAccessTokenResponse
     */
    token?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePersonalAccessTokenResponse
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreatePersonalAccessTokenResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CreatePersonalAccessTokenResponse interface.
 */
export function instanceOfCreatePersonalAccessTokenResponse(value: object): boolean {
    return true;
}

export function CreatePersonalAccessTokenResponseFromJSON(json: any): CreatePersonalAccessTokenResponse {
    return CreatePersonalAccessTokenResponseFromJSONTyped(json, false);
}

export function CreatePersonalAccessTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePersonalAccessTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'token': json['token'] == null ? undefined : json['token'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function CreatePersonalAccessTokenResponseToJSON(value?: CreatePersonalAccessTokenResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'token': value['token'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
    };
}

