/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMatchFlagRequest
 */
export interface CreateMatchFlagRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateMatchFlagRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the CreateMatchFlagRequest interface.
 */
export function instanceOfCreateMatchFlagRequest(value: object): boolean {
    if (!('reason' in value)) return false;
    return true;
}

export function CreateMatchFlagRequestFromJSON(json: any): CreateMatchFlagRequest {
    return CreateMatchFlagRequestFromJSONTyped(json, false);
}

export function CreateMatchFlagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMatchFlagRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function CreateMatchFlagRequestToJSON(value?: CreateMatchFlagRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reason': value['reason'],
    };
}

