/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePersonalAccessTokenRequest
 */
export interface CreatePersonalAccessTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePersonalAccessTokenRequest
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePersonalAccessTokenRequest
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the CreatePersonalAccessTokenRequest interface.
 */
export function instanceOfCreatePersonalAccessTokenRequest(value: object): boolean {
    return true;
}

export function CreatePersonalAccessTokenRequestFromJSON(json: any): CreatePersonalAccessTokenRequest {
    return CreatePersonalAccessTokenRequestFromJSONTyped(json, false);
}

export function CreatePersonalAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePersonalAccessTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function CreatePersonalAccessTokenRequestToJSON(value?: CreatePersonalAccessTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
    };
}

