/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaderboardEntry
 */
export interface LeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardEntry
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    mmr?: number;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    loses: number;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    winningStreak: number;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntry
     */
    losingStreak: number;
}

/**
 * Check if a given object implements the LeaderboardEntry interface.
 */
export function instanceOfLeaderboardEntry(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('name' in value)) return false;
    if (!('wins' in value)) return false;
    if (!('loses' in value)) return false;
    if (!('winningStreak' in value)) return false;
    if (!('losingStreak' in value)) return false;
    return true;
}

export function LeaderboardEntryFromJSON(json: any): LeaderboardEntry {
    return LeaderboardEntryFromJSONTyped(json, false);
}

export function LeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'mmr': json['mmr'] == null ? undefined : json['mmr'],
        'wins': json['wins'],
        'loses': json['loses'],
        'winningStreak': json['winningStreak'],
        'losingStreak': json['losingStreak'],
    };
}

export function LeaderboardEntryToJSON(value?: LeaderboardEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'mmr': value['mmr'],
        'wins': value['wins'],
        'loses': value['loses'],
        'winningStreak': value['winningStreak'],
        'losingStreak': value['losingStreak'],
    };
}

