/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchMMRCalculationTeam
 */
export interface MatchMMRCalculationTeam {
    /**
     * 
     * @type {number}
     * @memberof MatchMMRCalculationTeam
     */
    player1MMRDelta: number;
    /**
     * 
     * @type {number}
     * @memberof MatchMMRCalculationTeam
     */
    player2MMRDelta: number;
}

/**
 * Check if a given object implements the MatchMMRCalculationTeam interface.
 */
export function instanceOfMatchMMRCalculationTeam(value: object): boolean {
    if (!('player1MMRDelta' in value)) return false;
    if (!('player2MMRDelta' in value)) return false;
    return true;
}

export function MatchMMRCalculationTeamFromJSON(json: any): MatchMMRCalculationTeam {
    return MatchMMRCalculationTeamFromJSONTyped(json, false);
}

export function MatchMMRCalculationTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchMMRCalculationTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'player1MMRDelta': json['player1MMRDelta'],
        'player2MMRDelta': json['player2MMRDelta'],
    };
}

export function MatchMMRCalculationTeamToJSON(value?: MatchMMRCalculationTeam | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'player1MMRDelta': value['player1MMRDelta'],
        'player2MMRDelta': value['player2MMRDelta'],
    };
}

