/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchMMRCalculationDetails } from './MatchMMRCalculationDetails';
import {
    MatchMMRCalculationDetailsFromJSON,
    MatchMMRCalculationDetailsFromJSONTyped,
    MatchMMRCalculationDetailsToJSON,
} from './MatchMMRCalculationDetails';
import type { MatchTeamV2 } from './MatchTeamV2';
import {
    MatchTeamV2FromJSON,
    MatchTeamV2FromJSONTyped,
    MatchTeamV2ToJSON,
} from './MatchTeamV2';

/**
 * 
 * @export
 * @interface MatchDetailsV2
 */
export interface MatchDetailsV2 {
    /**
     * 
     * @type {Date}
     * @memberof MatchDetailsV2
     */
    date: Date;
    /**
     * 
     * @type {MatchTeamV2}
     * @memberof MatchDetailsV2
     */
    team1: MatchTeamV2;
    /**
     * 
     * @type {MatchTeamV2}
     * @memberof MatchDetailsV2
     */
    team2: MatchTeamV2;
    /**
     * 
     * @type {MatchMMRCalculationDetails}
     * @memberof MatchDetailsV2
     */
    mmrCalculations?: MatchMMRCalculationDetails;
}

/**
 * Check if a given object implements the MatchDetailsV2 interface.
 */
export function instanceOfMatchDetailsV2(value: object): boolean {
    if (!('date' in value)) return false;
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    return true;
}

export function MatchDetailsV2FromJSON(json: any): MatchDetailsV2 {
    return MatchDetailsV2FromJSONTyped(json, false);
}

export function MatchDetailsV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchDetailsV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'team1': MatchTeamV2FromJSON(json['team1']),
        'team2': MatchTeamV2FromJSON(json['team2']),
        'mmrCalculations': json['mmrCalculations'] == null ? undefined : MatchMMRCalculationDetailsFromJSON(json['mmrCalculations']),
    };
}

export function MatchDetailsV2ToJSON(value?: MatchDetailsV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': ((value['date']).toISOString()),
        'team1': MatchTeamV2ToJSON(value['team1']),
        'team2': MatchTeamV2ToJSON(value['team2']),
        'mmrCalculations': MatchMMRCalculationDetailsToJSON(value['mmrCalculations']),
    };
}

