/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchMakingQueueStatusPendingMatch } from './MatchMakingQueueStatusPendingMatch';
import {
    MatchMakingQueueStatusPendingMatchFromJSON,
    MatchMakingQueueStatusPendingMatchFromJSONTyped,
    MatchMakingQueueStatusPendingMatchToJSON,
} from './MatchMakingQueueStatusPendingMatch';

/**
 * 
 * @export
 * @interface MatchMakingQueueStatus
 */
export interface MatchMakingQueueStatus {
    /**
     * 
     * @type {boolean}
     * @memberof MatchMakingQueueStatus
     */
    isUserInQueue: boolean;
    /**
     * 
     * @type {number}
     * @memberof MatchMakingQueueStatus
     */
    playersInQueue: number;
    /**
     * 
     * @type {MatchMakingQueueStatusPendingMatch}
     * @memberof MatchMakingQueueStatus
     */
    assignedPendingMatch?: MatchMakingQueueStatusPendingMatch;
}

/**
 * Check if a given object implements the MatchMakingQueueStatus interface.
 */
export function instanceOfMatchMakingQueueStatus(value: object): boolean {
    if (!('isUserInQueue' in value)) return false;
    if (!('playersInQueue' in value)) return false;
    return true;
}

export function MatchMakingQueueStatusFromJSON(json: any): MatchMakingQueueStatus {
    return MatchMakingQueueStatusFromJSONTyped(json, false);
}

export function MatchMakingQueueStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchMakingQueueStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'isUserInQueue': json['isUserInQueue'],
        'playersInQueue': json['playersInQueue'],
        'assignedPendingMatch': json['assignedPendingMatch'] == null ? undefined : MatchMakingQueueStatusPendingMatchFromJSON(json['assignedPendingMatch']),
    };
}

export function MatchMakingQueueStatusToJSON(value?: MatchMakingQueueStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isUserInQueue': value['isUserInQueue'],
        'playersInQueue': value['playersInQueue'],
        'assignedPendingMatch': MatchMakingQueueStatusPendingMatchToJSON(value['assignedPendingMatch']),
    };
}

