/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MatchFlagStatus = {
    Pending: 'Pending',
    Resolved: 'Resolved'
} as const;
export type MatchFlagStatus = typeof MatchFlagStatus[keyof typeof MatchFlagStatus];


export function instanceOfMatchFlagStatus(value: any): boolean {
    return Object.values(MatchFlagStatus).includes(value);
}

export function MatchFlagStatusFromJSON(json: any): MatchFlagStatus {
    return MatchFlagStatusFromJSONTyped(json, false);
}

export function MatchFlagStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchFlagStatus {
    return json as MatchFlagStatus;
}

export function MatchFlagStatusToJSON(value?: MatchFlagStatus | null): any {
    return value as any;
}

