/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchDetailsV2 } from './MatchDetailsV2';
import {
    MatchDetailsV2FromJSON,
    MatchDetailsV2FromJSONTyped,
    MatchDetailsV2ToJSON,
} from './MatchDetailsV2';
import type { MatchFlagStatus } from './MatchFlagStatus';
import {
    MatchFlagStatusFromJSON,
    MatchFlagStatusFromJSONTyped,
    MatchFlagStatusToJSON,
} from './MatchFlagStatus';

/**
 * 
 * @export
 * @interface MatchFlagDetails
 */
export interface MatchFlagDetails {
    /**
     * 
     * @type {number}
     * @memberof MatchFlagDetails
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof MatchFlagDetails
     */
    matchId: number;
    /**
     * 
     * @type {MatchDetailsV2}
     * @memberof MatchFlagDetails
     */
    match: MatchDetailsV2;
    /**
     * 
     * @type {string}
     * @memberof MatchFlagDetails
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof MatchFlagDetails
     */
    flaggedByName: string;
    /**
     * 
     * @type {number}
     * @memberof MatchFlagDetails
     */
    flaggedById: number;
    /**
     * 
     * @type {Date}
     * @memberof MatchFlagDetails
     */
    createdAt: Date;
    /**
     * 
     * @type {MatchFlagStatus}
     * @memberof MatchFlagDetails
     */
    status: MatchFlagStatus;
    /**
     * 
     * @type {string}
     * @memberof MatchFlagDetails
     */
    resolutionNote?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchFlagDetails
     */
    resolvedByName?: string;
    /**
     * 
     * @type {Date}
     * @memberof MatchFlagDetails
     */
    resolvedAt?: Date;
}

/**
 * Check if a given object implements the MatchFlagDetails interface.
 */
export function instanceOfMatchFlagDetails(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('matchId' in value)) return false;
    if (!('match' in value)) return false;
    if (!('reason' in value)) return false;
    if (!('flaggedByName' in value)) return false;
    if (!('flaggedById' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function MatchFlagDetailsFromJSON(json: any): MatchFlagDetails {
    return MatchFlagDetailsFromJSONTyped(json, false);
}

export function MatchFlagDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchFlagDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'matchId': json['matchId'],
        'match': MatchDetailsV2FromJSON(json['match']),
        'reason': json['reason'],
        'flaggedByName': json['flaggedByName'],
        'flaggedById': json['flaggedById'],
        'createdAt': (new Date(json['createdAt'])),
        'status': MatchFlagStatusFromJSON(json['status']),
        'resolutionNote': json['resolutionNote'] == null ? undefined : json['resolutionNote'],
        'resolvedByName': json['resolvedByName'] == null ? undefined : json['resolvedByName'],
        'resolvedAt': json['resolvedAt'] == null ? undefined : (new Date(json['resolvedAt'])),
    };
}

export function MatchFlagDetailsToJSON(value?: MatchFlagDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'matchId': value['matchId'],
        'match': MatchDetailsV2ToJSON(value['match']),
        'reason': value['reason'],
        'flaggedByName': value['flaggedByName'],
        'flaggedById': value['flaggedById'],
        'createdAt': ((value['createdAt']).toISOString()),
        'status': MatchFlagStatusToJSON(value['status']),
        'resolutionNote': value['resolutionNote'],
        'resolvedByName': value['resolvedByName'],
        'resolvedAt': value['resolvedAt'] == null ? undefined : ((value['resolvedAt'] as any).toISOString()),
    };
}

