/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PendingMatchStatus } from './PendingMatchStatus';
import {
    PendingMatchStatusFromJSON,
    PendingMatchStatusFromJSONTyped,
    PendingMatchStatusToJSON,
} from './PendingMatchStatus';

/**
 * 
 * @export
 * @interface MatchMakingQueueStatusPendingMatch
 */
export interface MatchMakingQueueStatusPendingMatch {
    /**
     * 
     * @type {string}
     * @memberof MatchMakingQueueStatusPendingMatch
     */
    id: string;
    /**
     * 
     * @type {PendingMatchStatus}
     * @memberof MatchMakingQueueStatusPendingMatch
     */
    status: PendingMatchStatus;
    /**
     * 
     * @type {Date}
     * @memberof MatchMakingQueueStatusPendingMatch
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the MatchMakingQueueStatusPendingMatch interface.
 */
export function instanceOfMatchMakingQueueStatusPendingMatch(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('status' in value)) return false;
    if (!('expiresAt' in value)) return false;
    return true;
}

export function MatchMakingQueueStatusPendingMatchFromJSON(json: any): MatchMakingQueueStatusPendingMatch {
    return MatchMakingQueueStatusPendingMatchFromJSONTyped(json, false);
}

export function MatchMakingQueueStatusPendingMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchMakingQueueStatusPendingMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': PendingMatchStatusFromJSON(json['status']),
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function MatchMakingQueueStatusPendingMatchToJSON(value?: MatchMakingQueueStatusPendingMatch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': PendingMatchStatusToJSON(value['status']),
        'expiresAt': ((value['expiresAt']).toISOString()),
    };
}

