/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchMMRCalculationTeam } from './MatchMMRCalculationTeam';
import {
    MatchMMRCalculationTeamFromJSON,
    MatchMMRCalculationTeamFromJSONTyped,
    MatchMMRCalculationTeamToJSON,
} from './MatchMMRCalculationTeam';

/**
 * 
 * @export
 * @interface MatchMMRCalculationDetails
 */
export interface MatchMMRCalculationDetails {
    /**
     * 
     * @type {MatchMMRCalculationTeam}
     * @memberof MatchMMRCalculationDetails
     */
    team1: MatchMMRCalculationTeam;
    /**
     * 
     * @type {MatchMMRCalculationTeam}
     * @memberof MatchMMRCalculationDetails
     */
    team2: MatchMMRCalculationTeam;
}

/**
 * Check if a given object implements the MatchMMRCalculationDetails interface.
 */
export function instanceOfMatchMMRCalculationDetails(value: object): boolean {
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    return true;
}

export function MatchMMRCalculationDetailsFromJSON(json: any): MatchMMRCalculationDetails {
    return MatchMMRCalculationDetailsFromJSONTyped(json, false);
}

export function MatchMMRCalculationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchMMRCalculationDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'team1': MatchMMRCalculationTeamFromJSON(json['team1']),
        'team2': MatchMMRCalculationTeamFromJSON(json['team2']),
    };
}

export function MatchMMRCalculationDetailsToJSON(value?: MatchMMRCalculationDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1': MatchMMRCalculationTeamToJSON(value['team1']),
        'team2': MatchMMRCalculationTeamToJSON(value['team2']),
    };
}

