/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonalAccessTokenResponse
 */
export interface PersonalAccessTokenResponse {
    /**
     * 
     * @type {number}
     * @memberof PersonalAccessTokenResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenResponse
     */
    lastUsedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenResponse
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PersonalAccessTokenResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the PersonalAccessTokenResponse interface.
 */
export function instanceOfPersonalAccessTokenResponse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    return true;
}

export function PersonalAccessTokenResponseFromJSON(json: any): PersonalAccessTokenResponse {
    return PersonalAccessTokenResponseFromJSONTyped(json, false);
}

export function PersonalAccessTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalAccessTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : (new Date(json['lastUsedAt'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function PersonalAccessTokenResponseToJSON(value?: PersonalAccessTokenResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'lastUsedAt': value['lastUsedAt'] == null ? undefined : ((value['lastUsedAt'] as any).toISOString()),
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
    };
}

