/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlayerRole = {
    User: 'User',
    Moderator: 'Moderator',
    Owner: 'Owner'
} as const;
export type PlayerRole = typeof PlayerRole[keyof typeof PlayerRole];


export function instanceOfPlayerRole(value: any): boolean {
    return Object.values(PlayerRole).includes(value);
}

export function PlayerRoleFromJSON(json: any): PlayerRole {
    return PlayerRoleFromJSONTyped(json, false);
}

export function PlayerRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerRole {
    return json as PlayerRole;
}

export function PlayerRoleToJSON(value?: PlayerRole | null): any {
    return value as any;
}

