/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerRole } from './PlayerRole';
import {
    PlayerRoleFromJSON,
    PlayerRoleFromJSONTyped,
    PlayerRoleToJSON,
} from './PlayerRole';

/**
 * 
 * @export
 * @interface PlayerRoleResponse
 */
export interface PlayerRoleResponse {
    /**
     * 
     * @type {PlayerRole}
     * @memberof PlayerRoleResponse
     */
    role?: PlayerRole;
}

/**
 * Check if a given object implements the PlayerRoleResponse interface.
 */
export function instanceOfPlayerRoleResponse(value: object): boolean {
    return true;
}

export function PlayerRoleResponseFromJSON(json: any): PlayerRoleResponse {
    return PlayerRoleResponseFromJSONTyped(json, false);
}

export function PlayerRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : PlayerRoleFromJSON(json['role']),
    };
}

export function PlayerRoleResponseToJSON(value?: PlayerRoleResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': PlayerRoleToJSON(value['role']),
    };
}

