/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilePermissionsDto
 */
export interface ProfilePermissionsDto {
    /**
     * 
     * @type {boolean}
     * @memberof ProfilePermissionsDto
     */
    isAdmin?: boolean;
}

/**
 * Check if a given object implements the ProfilePermissionsDto interface.
 */
export function instanceOfProfilePermissionsDto(value: object): boolean {
    return true;
}

export function ProfilePermissionsDtoFromJSON(json: any): ProfilePermissionsDto {
    return ProfilePermissionsDtoFromJSONTyped(json, false);
}

export function ProfilePermissionsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilePermissionsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
    };
}

export function ProfilePermissionsDtoToJSON(value?: ProfilePermissionsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isAdmin': value['isAdmin'],
    };
}

