/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeasonDto
 */
export interface SeasonDto {
    /**
     * 
     * @type {number}
     * @memberof SeasonDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SeasonDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the SeasonDto interface.
 */
export function instanceOfSeasonDto(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function SeasonDtoFromJSON(json: any): SeasonDto {
    return SeasonDtoFromJSONTyped(json, false);
}

export function SeasonDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function SeasonDtoToJSON(value?: SeasonDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
    };
}

