/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchTeamV2 } from './MatchTeamV2';
import {
    MatchTeamV2FromJSON,
    MatchTeamV2FromJSONTyped,
    MatchTeamV2ToJSON,
} from './MatchTeamV2';

/**
 * 
 * @export
 * @interface SubmitMatchV2Request
 */
export interface SubmitMatchV2Request {
    /**
     * 
     * @type {MatchTeamV2}
     * @memberof SubmitMatchV2Request
     */
    team1: MatchTeamV2;
    /**
     * 
     * @type {MatchTeamV2}
     * @memberof SubmitMatchV2Request
     */
    team2: MatchTeamV2;
}

/**
 * Check if a given object implements the SubmitMatchV2Request interface.
 */
export function instanceOfSubmitMatchV2Request(value: object): boolean {
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    return true;
}

export function SubmitMatchV2RequestFromJSON(json: any): SubmitMatchV2Request {
    return SubmitMatchV2RequestFromJSONTyped(json, false);
}

export function SubmitMatchV2RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitMatchV2Request {
    if (json == null) {
        return json;
    }
    return {
        
        'team1': MatchTeamV2FromJSON(json['team1']),
        'team2': MatchTeamV2FromJSON(json['team2']),
    };
}

export function SubmitMatchV2RequestToJSON(value?: SubmitMatchV2Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1': MatchTeamV2ToJSON(value['team1']),
        'team2': MatchTeamV2ToJSON(value['team2']),
    };
}

