/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeStatisticsEntry
 */
export interface TimeStatisticsEntry {
    /**
     * 
     * @type {number}
     * @memberof TimeStatisticsEntry
     */
    dayOfWeek: number;
    /**
     * 
     * @type {number}
     * @memberof TimeStatisticsEntry
     */
    hourOfDay: number;
    /**
     * 
     * @type {number}
     * @memberof TimeStatisticsEntry
     */
    count: number;
}

/**
 * Check if a given object implements the TimeStatisticsEntry interface.
 */
export function instanceOfTimeStatisticsEntry(value: object): boolean {
    if (!('dayOfWeek' in value)) return false;
    if (!('hourOfDay' in value)) return false;
    if (!('count' in value)) return false;
    return true;
}

export function TimeStatisticsEntryFromJSON(json: any): TimeStatisticsEntry {
    return TimeStatisticsEntryFromJSONTyped(json, false);
}

export function TimeStatisticsEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeStatisticsEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'dayOfWeek': json['dayOfWeek'],
        'hourOfDay': json['hourOfDay'],
        'count': json['count'],
    };
}

export function TimeStatisticsEntryToJSON(value?: TimeStatisticsEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dayOfWeek': value['dayOfWeek'],
        'hourOfDay': value['hourOfDay'],
        'count': value['count'],
    };
}

