/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchTeamV2 } from './MatchTeamV2';
import {
    MatchTeamV2FromJSON,
    MatchTeamV2FromJSONTyped,
    MatchTeamV2ToJSON,
} from './MatchTeamV2';

/**
 * 
 * @export
 * @interface UpdateMatchRequest
 */
export interface UpdateMatchRequest {
    /**
     * 
     * @type {MatchTeamV2}
     * @memberof UpdateMatchRequest
     */
    team1: MatchTeamV2;
    /**
     * 
     * @type {MatchTeamV2}
     * @memberof UpdateMatchRequest
     */
    team2: MatchTeamV2;
    /**
     * 
     * @type {number}
     * @memberof UpdateMatchRequest
     */
    seasonId: number;
}

/**
 * Check if a given object implements the UpdateMatchRequest interface.
 */
export function instanceOfUpdateMatchRequest(value: object): boolean {
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    if (!('seasonId' in value)) return false;
    return true;
}

export function UpdateMatchRequestFromJSON(json: any): UpdateMatchRequest {
    return UpdateMatchRequestFromJSONTyped(json, false);
}

export function UpdateMatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'team1': MatchTeamV2FromJSON(json['team1']),
        'team2': MatchTeamV2FromJSON(json['team2']),
        'seasonId': json['seasonId'],
    };
}

export function UpdateMatchRequestToJSON(value?: UpdateMatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1': MatchTeamV2ToJSON(value['team1']),
        'team2': MatchTeamV2ToJSON(value['team2']),
        'seasonId': value['seasonId'],
    };
}

