/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchFlagStatus } from './MatchFlagStatus';
import {
    MatchFlagStatusFromJSON,
    MatchFlagStatusFromJSONTyped,
    MatchFlagStatusToJSON,
} from './MatchFlagStatus';

/**
 * 
 * @export
 * @interface UpdateMatchFlagRequest
 */
export interface UpdateMatchFlagRequest {
    /**
     * 
     * @type {MatchFlagStatus}
     * @memberof UpdateMatchFlagRequest
     */
    status: MatchFlagStatus;
    /**
     * 
     * @type {string}
     * @memberof UpdateMatchFlagRequest
     */
    note?: string;
}

/**
 * Check if a given object implements the UpdateMatchFlagRequest interface.
 */
export function instanceOfUpdateMatchFlagRequest(value: object): boolean {
    if (!('status' in value)) return false;
    return true;
}

export function UpdateMatchFlagRequestFromJSON(json: any): UpdateMatchFlagRequest {
    return UpdateMatchFlagRequestFromJSONTyped(json, false);
}

export function UpdateMatchFlagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMatchFlagRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': MatchFlagStatusFromJSON(json['status']),
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function UpdateMatchFlagRequestToJSON(value?: UpdateMatchFlagRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': MatchFlagStatusToJSON(value['status']),
        'note': value['note'],
    };
}

