/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateMatchFlagReasonRequest
 */
export interface UpdateMatchFlagReasonRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMatchFlagReasonRequest
   */
  reason: string;
}

/**
 * Check if a given object implements the UpdateMatchFlagReasonRequest interface.
 */
export function instanceOfUpdateMatchFlagReasonRequest(value: object): boolean {
  if (!('reason' in value)) return false;
  return true;
}

export function UpdateMatchFlagReasonRequestFromJSON(
  json: any
): UpdateMatchFlagReasonRequest {
  return UpdateMatchFlagReasonRequestFromJSONTyped(json, false);
}

export function UpdateMatchFlagReasonRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateMatchFlagReasonRequest {
  if (json == null) {
    return json;
  }
  return {
    reason: json['reason'],
  };
}

export function UpdateMatchFlagReasonRequestToJSON(
  value?: UpdateMatchFlagReasonRequest | null
): any {
  if (value == null) {
    return value;
  }
  return {
    reason: value['reason'],
  };
}
