/* tslint:disable */
/* eslint-disable */
/**
 * MMRProject.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserMatchFlag
 */
export interface UserMatchFlag {
  /**
   *
   * @type {number}
   * @memberof UserMatchFlag
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof UserMatchFlag
   */
  matchId?: number;
  /**
   *
   * @type {string}
   * @memberof UserMatchFlag
   */
  reason?: string;
  /**
   *
   * @type {Date}
   * @memberof UserMatchFlag
   */
  createdAt?: Date;
}

/**
 * Check if a given object implements the UserMatchFlag interface.
 */
export function instanceOfUserMatchFlag(value: object): boolean {
  return true;
}

export function UserMatchFlagFromJSON(json: any): UserMatchFlag {
  return UserMatchFlagFromJSONTyped(json, false);
}

export function UserMatchFlagFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserMatchFlag {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    matchId: json['matchId'] == null ? undefined : json['matchId'],
    reason: json['reason'] == null ? undefined : json['reason'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
  };
}

export function UserMatchFlagToJSON(value?: UserMatchFlag | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    matchId: value['matchId'],
    reason: value['reason'],
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
  };
}
