// <auto-generated />
using System;
using MMRProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MMRProject.Api.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260315002046_AddOrganizationInviteLinks")]
    partial class AddOrganizationInviteLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MMRProject.Api.Data.Entities.ActiveMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TeamOnePlayerOneId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamOnePlayerTwoId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamTwoPlayerOneId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamTwoPlayerTwoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamOnePlayerOneId");

                    b.HasIndex("TeamOnePlayerTwoId");

                    b.HasIndex("TeamTwoPlayerOneId");

                    b.HasIndex("TeamTwoPlayerTwoId");

                    b.ToTable("ActiveMatches");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<long?>("TeamOneId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_one_id");

                    b.Property<long?>("TeamTwoId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_two_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("matches_pkey");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamOneId");

                    b.HasIndex("TeamTwoId");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_matches_deleted_at");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.MatchFlag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FlaggedById")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ResolvedById")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FlaggedById");

                    b.HasIndex("ResolvedById");

                    b.HasIndex("MatchId", "FlaggedById")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchFlags_MatchId_FlaggedById_Pending")
                        .HasFilter("\"Status\" = 0 AND \"DeletedAt\" IS NULL");

                    b.ToTable("MatchFlags");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.MmrCalculation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("MatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("match_id");

                    b.Property<long?>("TeamOnePlayerOneMmrDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("team_one_player_one_mmr_delta");

                    b.Property<long?>("TeamOnePlayerTwoMmrDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("team_one_player_two_mmr_delta");

                    b.Property<long?>("TeamTwoPlayerOneMmrDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("team_two_player_one_mmr_delta");

                    b.Property<long?>("TeamTwoPlayerTwoMmrDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("team_two_player_two_mmr_delta");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("mmr_calculations_pkey");

                    b.HasIndex("MatchId");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_mmr_calculations_deleted_at");

                    b.ToTable("mmr_calculations", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PendingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveMatchId")
                        .IsUnique();

                    b.ToTable("PendingMatches");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PersonalAccessToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TokenHash");

                    b.ToTable("PersonalAccessTokens");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.Property<DateTime?>("MigratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("migrated_at");

                    b.Property<long?>("Mmr")
                        .HasColumnType("bigint")
                        .HasColumnName("mmr");

                    b.Property<decimal?>("Mu")
                        .HasColumnType("numeric")
                        .HasColumnName("mu");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RoleAssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("RoleAssignedById")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Sigma")
                        .HasColumnType("numeric")
                        .HasColumnName("sigma");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleAssignedById");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_players_deleted_at");

                    b.HasIndex(new[] { "Email" }, "idx_players_email");

                    b.HasIndex(new[] { "Id" }, "players_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "IdentityUserId" }, "uni_players_identity_user_id")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "uni_players_name")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PlayerHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("MatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("match_id");

                    b.Property<long?>("Mmr")
                        .HasColumnType("bigint")
                        .HasColumnName("mmr");

                    b.Property<decimal?>("Mu")
                        .HasColumnType("numeric")
                        .HasColumnName("mu");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<decimal?>("Sigma")
                        .HasColumnType("numeric")
                        .HasColumnName("sigma");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("player_histories_pkey");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_player_histories_deleted_at");

                    b.ToTable("player_histories", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.QueuedPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastAcceptedMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PendingMatchId")
                        .HasColumnType("uuid");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PendingMatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("QueuedPlayers");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("seasons_pkey");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_seasons_deleted_at");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("PlayerOneId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_one_id");

                    b.Property<long?>("PlayerTwoId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_two_id");

                    b.Property<long?>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("Winner")
                        .HasColumnType("boolean")
                        .HasColumnName("winner");

                    b.HasKey("Id")
                        .HasName("teams_pkey");

                    b.HasIndex("PlayerOneId");

                    b.HasIndex("PlayerTwoId");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_teams_deleted_at");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("QueueSize")
                        .HasColumnType("integer")
                        .HasColumnName("queue_size");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrganizationId", "Slug" }, "ix_v3_leagues_org_slug")
                        .IsUnique();

                    b.ToTable("v3_leagues", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.LeaguePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<long?>("LegacyPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_player_id");

                    b.Property<long>("Mmr")
                        .HasColumnType("bigint")
                        .HasColumnName("mmr");

                    b.Property<decimal>("Mu")
                        .HasColumnType("numeric")
                        .HasColumnName("mu");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("OrganizationMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_membership_id");

                    b.Property<decimal>("Sigma")
                        .HasColumnType("numeric")
                        .HasColumnName("sigma");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationMembershipId");

                    b.HasIndex(new[] { "LeagueId", "OrganizationMembershipId" }, "ix_v3_league_players_league_membership")
                        .IsUnique();

                    b.ToTable("v3_league_players", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.MatchTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_winner");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MatchId" }, "ix_v3_match_teams_match");

                    b.ToTable("v3_match_teams", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.MatchTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("LeaguePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_player_id");

                    b.Property<Guid>("MatchTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_team_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("LeaguePlayerId");

                    b.HasIndex("MatchTeamId");

                    b.ToTable("v3_match_team_players", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Slug" }, "ix_v3_organizations_slug")
                        .IsUnique();

                    b.ToTable("v3_organizations", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.OrganizationInviteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMembershipId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex(new[] { "Code" }, "ix_v3_organization_invite_links_code")
                        .IsUnique();

                    b.ToTable("v3_organization_invite_links", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("InviteEmail")
                        .HasColumnType("text")
                        .HasColumnName("invite_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("RoleAssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("role_assigned_at");

                    b.Property<Guid?>("RoleAssignedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_assigned_by_membership_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("RoleAssignedByMembershipId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "OrganizationId", "InviteEmail" }, "ix_v3_organization_memberships_org_invite_email")
                        .IsUnique()
                        .HasFilter("invite_email IS NOT NULL");

                    b.HasIndex(new[] { "OrganizationId", "UserId" }, "ix_v3_organization_memberships_org_user")
                        .IsUnique()
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("v3_organization_memberships", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeaguePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_player_id");

                    b.Property<Guid>("PendingMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_match_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LeaguePlayerId");

                    b.HasIndex("PendingMatchId");

                    b.ToTable("v3_pending_match_acceptances", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PendingMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_match_id");

                    b.HasKey("Id");

                    b.HasIndex("PendingMatchId");

                    b.ToTable("v3_pending_match_teams", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("LeaguePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_player_id");

                    b.Property<Guid>("PendingMatchTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_match_team_id");

                    b.HasKey("Id");

                    b.HasIndex("LeaguePlayerId");

                    b.HasIndex("PendingMatchTeamId");

                    b.ToTable("v3_pending_match_team_players", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("LeaguePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_player_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("LeaguePlayerId");

                    b.HasIndex(new[] { "LeagueId", "LeaguePlayerId" }, "ix_v3_queue_entries_league_player")
                        .IsUnique();

                    b.ToTable("v3_queue_entries", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.RatingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Delta")
                        .HasColumnType("bigint")
                        .HasColumnName("delta");

                    b.Property<Guid>("LeaguePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_player_id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<long>("Mmr")
                        .HasColumnType("bigint")
                        .HasColumnName("mmr");

                    b.Property<decimal>("Mu")
                        .HasColumnType("numeric")
                        .HasColumnName("mu");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("Sigma")
                        .HasColumnType("numeric")
                        .HasColumnName("sigma");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex(new[] { "LeaguePlayerId", "MatchId" }, "ix_v3_rating_histories_player_match");

                    b.ToTable("v3_rating_histories", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.Property<long?>("LegacyPlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_player_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "ix_v3_users_email");

                    b.HasIndex(new[] { "IdentityUserId" }, "ix_v3_users_identity_user_id")
                        .IsUnique();

                    b.ToTable("v3_users", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3ActiveMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PendingMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_match_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("PendingMatchId");

                    b.ToTable("v3_active_matches", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_membership_id");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<long?>("LegacyMatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_match_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMembershipId");

                    b.HasIndex("SeasonId");

                    b.HasIndex(new[] { "LeagueId", "SeasonId" }, "ix_v3_matches_league_season");

                    b.ToTable("v3_matches", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3MatchFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FlaggedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("flagged_by_membership_id");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_membership_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FlaggedByMembershipId");

                    b.HasIndex("ResolvedByMembershipId");

                    b.HasIndex(new[] { "LeagueId", "MatchId" }, "ix_v3_match_flags_league_match");

                    b.HasIndex(new[] { "MatchId", "FlaggedByMembershipId" }, "ix_v3_match_flags_match_flagged_by_open")
                        .IsUnique()
                        .HasFilter("status = 0");

                    b.ToTable("v3_match_flags", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3PendingMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("v3_pending_matches", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3PersonalAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<long?>("LegacyPatId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_pat_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TokenHash" }, "ix_v3_personal_access_tokens_token_hash");

                    b.ToTable("v3_personal_access_tokens", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<long?>("LegacySeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_season_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LeagueId" }, "ix_v3_seasons_league");

                    b.ToTable("v3_seasons", (string)null);
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.ActiveMatch", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Player", "TeamOnePlayerOne")
                        .WithMany()
                        .HasForeignKey("TeamOnePlayerOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "TeamOnePlayerTwo")
                        .WithMany()
                        .HasForeignKey("TeamOnePlayerTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "TeamTwoPlayerOne")
                        .WithMany()
                        .HasForeignKey("TeamTwoPlayerOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "TeamTwoPlayerTwo")
                        .WithMany()
                        .HasForeignKey("TeamTwoPlayerTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamOnePlayerOne");

                    b.Navigation("TeamOnePlayerTwo");

                    b.Navigation("TeamTwoPlayerOne");

                    b.Navigation("TeamTwoPlayerTwo");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Match", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("fk_matches_season");

                    b.HasOne("MMRProject.Api.Data.Entities.Team", "TeamOne")
                        .WithMany("MatchTeamOnes")
                        .HasForeignKey("TeamOneId")
                        .HasConstraintName("fk_matches_team_one");

                    b.HasOne("MMRProject.Api.Data.Entities.Team", "TeamTwo")
                        .WithMany("MatchTeamTwos")
                        .HasForeignKey("TeamTwoId")
                        .HasConstraintName("fk_matches_team_two");

                    b.Navigation("Season");

                    b.Navigation("TeamOne");

                    b.Navigation("TeamTwo");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.MatchFlag", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Player", "FlaggedBy")
                        .WithMany()
                        .HasForeignKey("FlaggedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMRProject.Api.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedById");

                    b.Navigation("FlaggedBy");

                    b.Navigation("Match");

                    b.Navigation("ResolvedBy");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.MmrCalculation", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Match", "Match")
                        .WithMany("MmrCalculations")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("fk_matches_mmr_calculations");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PendingMatch", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.ActiveMatch", "ActiveMatch")
                        .WithOne("PendingMatch")
                        .HasForeignKey("MMRProject.Api.Data.Entities.PendingMatch", "ActiveMatchId");

                    b.Navigation("ActiveMatch");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PersonalAccessToken", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Player", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Player", "RoleAssignedBy")
                        .WithMany()
                        .HasForeignKey("RoleAssignedById");

                    b.Navigation("RoleAssignedBy");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PlayerHistory", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Match", "Match")
                        .WithMany("PlayerHistories")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("fk_player_histories_match");

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "Player")
                        .WithMany("PlayerHistories")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("fk_player_histories_player");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.QueuedPlayer", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.PendingMatch", "PendingMatch")
                        .WithMany("QueuedPlayers")
                        .HasForeignKey("PendingMatchId");

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingMatch");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Team", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.Player", "PlayerOne")
                        .WithMany("TeamPlayerOnes")
                        .HasForeignKey("PlayerOneId")
                        .HasConstraintName("fk_teams_player_one");

                    b.HasOne("MMRProject.Api.Data.Entities.Player", "PlayerTwo")
                        .WithMany("TeamPlayerTwos")
                        .HasForeignKey("PlayerTwoId")
                        .HasConstraintName("fk_teams_play_two");

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerTwo");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.League", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_leagues_organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.LeaguePlayer", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_league_players_league");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.OrganizationMembership", "OrganizationMembership")
                        .WithMany()
                        .HasForeignKey("OrganizationMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_league_players_membership");

                    b.Navigation("League");

                    b.Navigation("OrganizationMembership");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.MatchTeam", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3Match", "Match")
                        .WithMany("Teams")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_match_teams_match");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.MatchTeamPlayer", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.LeaguePlayer", "LeaguePlayer")
                        .WithMany()
                        .HasForeignKey("LeaguePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_match_team_players_player");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.MatchTeam", "MatchTeam")
                        .WithMany("Players")
                        .HasForeignKey("MatchTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_match_team_players_team");

                    b.Navigation("LeaguePlayer");

                    b.Navigation("MatchTeam");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.OrganizationInviteLink", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.OrganizationMembership", "CreatedByMembership")
                        .WithMany()
                        .HasForeignKey("CreatedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_organization_invite_links_created_by");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_organization_invite_links_organization");

                    b.Navigation("CreatedByMembership");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.OrganizationMembership", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_organization_memberships_organization");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.OrganizationMembership", "RoleAssignedByMembership")
                        .WithMany()
                        .HasForeignKey("RoleAssignedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_v3_organization_memberships_role_assigned_by");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_v3_organization_memberships_user");

                    b.Navigation("Organization");

                    b.Navigation("RoleAssignedByMembership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchAcceptance", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.LeaguePlayer", "LeaguePlayer")
                        .WithMany()
                        .HasForeignKey("LeaguePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_pending_match_acceptances_player");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3PendingMatch", "PendingMatch")
                        .WithMany("Acceptances")
                        .HasForeignKey("PendingMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_pending_match_acceptances_pending_match");

                    b.Navigation("LeaguePlayer");

                    b.Navigation("PendingMatch");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchTeam", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3PendingMatch", "PendingMatch")
                        .WithMany("Teams")
                        .HasForeignKey("PendingMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_pending_match_teams_pending_match");

                    b.Navigation("PendingMatch");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchTeamPlayer", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.LeaguePlayer", "LeaguePlayer")
                        .WithMany()
                        .HasForeignKey("LeaguePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_pending_match_team_players_player");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.PendingMatchTeam", "PendingMatchTeam")
                        .WithMany("Players")
                        .HasForeignKey("PendingMatchTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_pending_match_team_players_team");

                    b.Navigation("LeaguePlayer");

                    b.Navigation("PendingMatchTeam");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.QueueEntry", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_queue_entries_league");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.LeaguePlayer", "LeaguePlayer")
                        .WithMany()
                        .HasForeignKey("LeaguePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_queue_entries_player");

                    b.Navigation("League");

                    b.Navigation("LeaguePlayer");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.RatingHistory", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.LeaguePlayer", "LeaguePlayer")
                        .WithMany()
                        .HasForeignKey("LeaguePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_rating_histories_player");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_rating_histories_match");

                    b.Navigation("LeaguePlayer");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3ActiveMatch", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3PendingMatch", "PendingMatch")
                        .WithMany()
                        .HasForeignKey("PendingMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_active_matches_pending_match");

                    b.Navigation("PendingMatch");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3Match", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.OrganizationMembership", "CreatedByMembership")
                        .WithMany()
                        .HasForeignKey("CreatedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_matches_created_by");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_matches_league");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_matches_season");

                    b.Navigation("CreatedByMembership");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3MatchFlag", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.OrganizationMembership", "FlaggedByMembership")
                        .WithMany()
                        .HasForeignKey("FlaggedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_match_flags_flagged_by");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.V3Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_match_flags_match");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.OrganizationMembership", "ResolvedByMembership")
                        .WithMany()
                        .HasForeignKey("ResolvedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_v3_match_flags_resolved_by");

                    b.Navigation("FlaggedByMembership");

                    b.Navigation("Match");

                    b.Navigation("ResolvedByMembership");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3PersonalAccessToken", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_v3_personal_access_tokens_league");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_v3_personal_access_tokens_organization");

                    b.HasOne("MMRProject.Api.Data.Entities.V3.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_personal_access_tokens_user");

                    b.Navigation("League");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3Season", b =>
                {
                    b.HasOne("MMRProject.Api.Data.Entities.V3.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_v3_seasons_league");

                    b.Navigation("League");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.ActiveMatch", b =>
                {
                    b.Navigation("PendingMatch");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Match", b =>
                {
                    b.Navigation("MmrCalculations");

                    b.Navigation("PlayerHistories");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.PendingMatch", b =>
                {
                    b.Navigation("QueuedPlayers");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Player", b =>
                {
                    b.Navigation("PlayerHistories");

                    b.Navigation("TeamPlayerOnes");

                    b.Navigation("TeamPlayerTwos");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Season", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.Team", b =>
                {
                    b.Navigation("MatchTeamOnes");

                    b.Navigation("MatchTeamTwos");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.MatchTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.PendingMatchTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3Match", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("MMRProject.Api.Data.Entities.V3.V3PendingMatch", b =>
                {
                    b.Navigation("Acceptances");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
