# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go - build and test (codecov)

on:
  push:
    branches: ["main"]
    paths:
      - "backend-dotnet/**/*"
      - ".github/workflows/deploy-api.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "backend-dotnet/**/*"
      - ".github/workflows/deploy-api.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
